name: Build and Test SpecFlow Project

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # O puedes elegir otro sistema operativo como windows-latest

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'  # Especifica la versión de .NET que estás utilizando

      # Paso 3: Restaurar las dependencias de NuGet
      - name: Restore dependencies
        run: dotnet restore NuGet.Config

      # Paso 4: Compilar el proyecto
      - name: Build project
        run: dotnet build SpecFlowSolution.sln --configuration Release
