name: SpecFlow Selenium Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    name: selenium-tests
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      # Paso 3: Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore ./SpecFlowSeleniumProject/SpecFlowSelenium/SpecflowSelenium.csproj --configfile ./SpecFlowSeleniumProject/NuGet.Config

      # Paso 4: Compilar el proyecto
      - name: Build project
        run: dotnet build ./SpecFlowSeleniumProject/SpecFlowSelenium/SpecflowSelenium.csproj --configuration Release
        
      # Paso 5: Ejecutar tests de SpecFlow
      - name: Run SpecFlow Tests
        run: dotnet test ./SpecFlowSeleniumProject/SpecFlowSelenium/SpecflowSelenium.csproj --configuration Release --no-build --logger "trx"
